version: '3.0'

services:
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./app:/symfony
    container_name: test-nginx
    restart: always
    ports:
      - "8081:80"

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./app:/symfony
    container_name: test-php-fpm

  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./app:/symfony
    command: sleep 10000
    container_name: test-php-cli